import type { Event, Venue } from "./types"

// Twin Cities Venues
export const venues: Venue[] = [
  {
    id: "first-ave",
    name: "First Avenue",
    neighborhood: "downtown-mpls",
    address: "701 1st Ave N, Minneapolis",
    capacity: "large",
  },
  {
    id: "7th-st-entry",
    name: "7th St Entry",
    neighborhood: "downtown-mpls",
    address: "701 1st Ave N, Minneapolis",
    capacity: "small",
  },
  {
    id: "turf-club",
    name: "Turf Club",
    neighborhood: "midway",
    address: "1601 University Ave W, St Paul",
    capacity: "medium",
  },
  {
    id: "amsterdam",
    name: "Amsterdam Bar & Hall",
    neighborhood: "st-paul-downtown",
    address: "6 W 6th St, St Paul",
    capacity: "medium",
  },
  {
    id: "icehouse",
    name: "Icehouse",
    neighborhood: "uptown",
    address: "2528 Nicollet Ave, Minneapolis",
    capacity: "small",
  },
  {
    id: "dakota",
    name: "Dakota Jazz Club",
    neighborhood: "downtown-mpls",
    address: "1010 Nicollet Mall, Minneapolis",
    capacity: "medium",
  },
  {
    id: "cedar",
    name: "The Cedar Cultural Center",
    neighborhood: "seward",
    address: "416 Cedar Ave, Minneapolis",
    capacity: "medium",
  },
  {
    id: "cabooze",
    name: "Cabooze",
    neighborhood: "seward",
    address: "917 Cedar Ave, Minneapolis",
    capacity: "large",
  },
  {
    id: "fine-line",
    name: "Fine Line",
    neighborhood: "downtown-mpls",
    address: "318 1st Ave N, Minneapolis",
    capacity: "medium",
  },
  {
    id: "palmers",
    name: "Palmer's Bar",
    neighborhood: "seward",
    address: "500 Cedar Ave, Minneapolis",
    capacity: "small",
  },
  {
    id: "hook-ladder",
    name: "Hook & Ladder Theater",
    neighborhood: "south-mpls",
    address: "3010 Minnehaha Ave, Minneapolis",
    capacity: "medium",
  },
  {
    id: "331-club",
    name: "331 Club",
    neighborhood: "ne-mpls",
    address: "331 13th Ave NE, Minneapolis",
    capacity: "small",
  },
  {
    id: "indeed-brewing",
    name: "Indeed Brewing Taproom",
    neighborhood: "ne-mpls",
    address: "711 15th Ave NE, Minneapolis",
    capacity: "medium",
  },
  {
    id: "surly",
    name: "Surly Brewing Festival Field",
    neighborhood: "south-mpls",
    address: "520 Malcolm Ave SE, Minneapolis",
    capacity: "large",
  },
  {
    id: "varsity",
    name: "Varsity Theater",
    neighborhood: "dinkytown",
    address: "1308 4th St SE, Minneapolis",
    capacity: "medium",
  },
  {
    id: "armory",
    name: "The Armory",
    neighborhood: "downtown-mpls",
    address: "500 S 6th St, Minneapolis",
    capacity: "large",
  },
  {
    id: "palace",
    name: "Palace Theatre",
    neighborhood: "st-paul-downtown",
    address: "17 W 7th Pl, St Paul",
    capacity: "large",
  },
  {
    id: "xcel",
    name: "Xcel Energy Center",
    neighborhood: "st-paul-downtown",
    address: "199 W Kellogg Blvd, St Paul",
    capacity: "large",
  },
  {
    id: "fillmore",
    name: "The Fillmore Minneapolis",
    neighborhood: "north-loop",
    address: "525 N 5th St, Minneapolis",
    capacity: "large",
  },
  {
    id: "white-squirrel",
    name: "White Squirrel Bar",
    neighborhood: "st-paul-downtown",
    address: "974 W 7th St, St Paul",
    capacity: "small",
  },
  {
    id: "clown-lounge",
    name: "Clown Lounge",
    neighborhood: "midway",
    address: "1601 University Ave W, St Paul",
    capacity: "small",
  },
  {
    id: "mortimers",
    name: "Mortimer's",
    neighborhood: "uptown",
    address: "2001 Lyndale Ave S, Minneapolis",
    capacity: "small",
  },
  {
    id: "can-can",
    name: "Can Can Wonderland",
    neighborhood: "midway",
    address: "755 Prior Ave N, St Paul",
    capacity: "medium",
  },
  {
    id: "mystic-lake",
    name: "Mystic Lake Casino",
    neighborhood: "suburbs",
    address: "2400 Mystic Lake Blvd, Prior Lake",
    capacity: "large",
  },
  {
    id: "treasure-island",
    name: "Treasure Island Amphitheater",
    neighborhood: "suburbs",
    address: "5734 Sturgeon Lake Rd, Welch",
    capacity: "large",
  },
  // Comedy Venues
  {
    id: "acme-comedy",
    name: "Acme Comedy Company",
    neighborhood: "downtown-mpls",
    address: "708 N 1st St, Minneapolis",
    capacity: "small",
  },
  {
    id: "house-of-comedy",
    name: "House of Comedy",
    neighborhood: "suburbs",
    address: "408 E Broadway, Mall of America, Bloomington",
    capacity: "medium",
  },
  {
    id: "comedy-corner",
    name: "Comedy Corner Underground",
    neighborhood: "dinkytown",
    address: "1501 S Washington Ave, Minneapolis",
    capacity: "small",
  },
  {
    id: "sisyphus",
    name: "Sisyphus Brewing",
    neighborhood: "ne-mpls",
    address: "712 Ontario Ave W, Minneapolis",
    capacity: "small",
  },
  {
    id: "huge-theater",
    name: "HUGE Improv Theater",
    neighborhood: "uptown",
    address: "3037 Lyndale Ave S, Minneapolis",
    capacity: "small",
  },
]

// Helper to generate dates
function getDate(daysFromNow: number): string {
  const date = new Date()
  date.setDate(date.getDate() + daysFromNow)
  return date.toISOString().split("T")[0]
}

// Mock Events
export const events: Event[] = [
  // Tonight / This Weekend - Higher profile shows
  {
    id: "1",
    artist: "Hippo Campus",
    venue: venues.find((v) => v.id === "first-ave")!,
    date: getDate(0),
    time: "8:00 PM",
    doors: "7:00 PM",
    price: { min: 35, max: 45 },
    ageRestriction: "18+",
    genres: ["indie", "rock"],
    mood: "chill",
    ticketUrl: "https://first-avenue.com",
    imageUrl: "/images/concert-folk.jpg",
    description:
      "Minnesota's own Hippo Campus returns home for a sold-out hometown show. Known for their dreamy indie rock sound, the band brings their latest album tour to First Avenue.",
    popularity: 85,
    isLocalArtist: true,
    supportingActs: ["Gully Boys", "Velvet Negroni"],
  },
  {
    id: "2",
    artist: "Trampled By Turtles",
    venue: venues.find((v) => v.id === "palace")!,
    date: getDate(1),
    time: "7:30 PM",
    doors: "6:30 PM",
    price: { min: 45, max: 65 },
    ageRestriction: "all-ages",
    genres: ["folk", "country"],
    mood: "chill",
    ticketUrl: "https://palacetheatre.us",
    imageUrl: "/images/concert-folk.jpg",
    description:
      "Duluth bluegrass legends Trampled By Turtles bring their high-energy acoustic sound to St Paul for two nights.",
    popularity: 80,
    isLocalArtist: true,
  },
  {
    id: "3",
    artist: "Doomtree",
    venue: venues.find((v) => v.id === "first-ave")!,
    date: getDate(2),
    time: "9:00 PM",
    doors: "8:00 PM",
    price: { min: 30, max: 40 },
    ageRestriction: "18+",
    genres: ["hip-hop"],
    mood: "heavy",
    ticketUrl: "https://first-avenue.com",
    imageUrl: "/images/concert-hiphop.jpg",
    description:
      "Minneapolis hip-hop collective Doomtree reunites for a rare full-crew performance. P.O.S, Dessa, Sims, Cecil Otter, Mike Mictlan, Paper Tiger, and Lazerbeak all under one roof.",
    popularity: 75,
    isLocalArtist: true,
  },
  {
    id: "4",
    artist: "GWAR",
    venue: venues.find((v) => v.id === "fillmore")!,
    date: getDate(3),
    time: "8:00 PM",
    doors: "7:00 PM",
    price: { min: 35, max: 50 },
    ageRestriction: "all-ages",
    genres: ["metal", "punk"],
    mood: "heavy",
    ticketUrl: "https://thefillmorempls.com",
    imageUrl: "/images/concert-rock.jpg",
    description:
      "The intergalactic shock-rock warriors return to Minneapolis. Expect fake blood, costumes, and crushing riffs. Wear clothes you don't mind getting destroyed.",
    popularity: 70,
    isLocalArtist: false,
  },
  {
    id: "5",
    artist: "Kathleen Edwards",
    venue: venues.find((v) => v.id === "cedar")!,
    date: getDate(4),
    time: "7:30 PM",
    doors: "6:30 PM",
    price: { min: 35, max: 45 },
    ageRestriction: "all-ages",
    genres: ["folk", "indie"],
    mood: "chill",
    ticketUrl: "https://thecedar.org",
    imageUrl: "/images/concert-folk.jpg",
    description:
      "Canadian singer-songwriter Kathleen Edwards performs songs from her acclaimed comeback album. A masterclass in heartfelt storytelling.",
    popularity: 55,
    isLocalArtist: false,
  },
  // Jazz Shows
  {
    id: "6",
    artist: "Ravi Coltrane Quartet",
    venue: venues.find((v) => v.id === "dakota")!,
    date: getDate(5),
    time: "7:00 PM",
    doors: "6:00 PM",
    price: { min: 40, max: 60 },
    ageRestriction: "all-ages",
    genres: ["jazz"],
    mood: "chill",
    ticketUrl: "https://dakotacooks.com",
    imageUrl: "/images/concert-jazz.jpg",
    description:
      "Saxophonist Ravi Coltrane, son of John and Alice Coltrane, brings his spiritually-charged modern jazz to the Dakota.",
    popularity: 50,
    isLocalArtist: false,
  },
  {
    id: "7",
    artist: "JT Bates & Friends",
    venue: venues.find((v) => v.id === "icehouse")!,
    date: getDate(0),
    time: "10:00 PM",
    doors: "9:00 PM",
    price: "free",
    ageRestriction: "21+",
    genres: ["jazz", "experimental"],
    mood: "experimental",
    ticketUrl: "https://icehousempls.com",
    imageUrl: "/images/concert-jazz.jpg",
    description:
      "Local jazz drummer JT Bates hosts his legendary late-night session. Who shows up is always a surprise. Past guests have included members of Bon Iver and The Bad Plus.",
    popularity: 35,
    isLocalArtist: true,
  },
  // Electronic / Dance
  {
    id: "8",
    artist: "Floating Points",
    venue: venues.find((v) => v.id === "fine-line")!,
    date: getDate(8),
    time: "10:00 PM",
    doors: "9:00 PM",
    price: { min: 35, max: 45 },
    ageRestriction: "18+",
    genres: ["electronic"],
    mood: "dancey",
    ticketUrl: "https://fineline.com",
    imageUrl: "/images/concert-electronic.jpg",
    description:
      "Sam Shepherd's Floating Points project brings his hypnotic electronic productions to Minneapolis. A DJ set spanning ambient, house, and jazz influences.",
    popularity: 60,
    isLocalArtist: false,
  },
  {
    id: "9",
    artist: "Derecho",
    venue: venues.find((v) => v.id === "indeed-brewing")!,
    date: getDate(6),
    time: "8:00 PM",
    doors: "7:00 PM",
    price: "free",
    ageRestriction: "21+",
    genres: ["electronic", "experimental"],
    mood: "dancey",
    ticketUrl: "https://indeedbrewing.com",
    imageUrl: "/images/concert-electronic.jpg",
    description:
      "Minneapolis electronic duo Derecho performs live modular synth compositions. Unpredictable, danceable, and always different.",
    popularity: 25,
    isLocalArtist: true,
  },
  // Punk / Heavy
  {
    id: "10",
    artist: "OFF!",
    venue: venues.find((v) => v.id === "turf-club")!,
    date: getDate(10),
    time: "8:00 PM",
    doors: "7:00 PM",
    price: { min: 25, max: 30 },
    ageRestriction: "21+",
    genres: ["punk", "rock"],
    mood: "heavy",
    ticketUrl: "https://turfclub.net",
    imageUrl: "/images/concert-rock.jpg",
    description:
      "Keith Morris (Black Flag, Circle Jerks) leads his hardcore punk supergroup OFF! through a blistering set of sub-two-minute bangers.",
    popularity: 55,
    isLocalArtist: false,
  },
  {
    id: "11",
    artist: "Dillinger Four",
    venue: venues.find((v) => v.id === "7th-st-entry")!,
    date: getDate(14),
    time: "9:00 PM",
    doors: "8:00 PM",
    price: { min: 20, max: 25 },
    ageRestriction: "18+",
    genres: ["punk"],
    mood: "heavy",
    ticketUrl: "https://first-avenue.com",
    imageUrl: "/images/concert-rock.jpg",
    description:
      "Minneapolis punk legends D4 play a rare hometown show. These Triple Rock founders helped define the Minneapolis punk sound.",
    popularity: 45,
    isLocalArtist: true,
  },
  // Small Shows / Deep Cuts
  {
    id: "12",
    artist: "Bad Bad Hats",
    venue: venues.find((v) => v.id === "331-club")!,
    date: getDate(7),
    time: "9:00 PM",
    doors: "8:00 PM",
    price: "free",
    ageRestriction: "21+",
    genres: ["indie", "pop"],
    mood: "chill",
    ticketUrl: "https://331club.com",
    imageUrl: "/images/concert-folk.jpg",
    description:
      "Twin Cities indie pop darlings Bad Bad Hats play a free Monday residency show. Kerry Alexander's clever songwriting in an intimate setting.",
    popularity: 40,
    isLocalArtist: true,
  },
  {
    id: "13",
    artist: "Night Moves",
    venue: venues.find((v) => v.id === "hook-ladder")!,
    date: getDate(9),
    time: "8:00 PM",
    doors: "7:00 PM",
    price: { min: 18, max: 22 },
    ageRestriction: "21+",
    genres: ["rock", "indie"],
    mood: "chill",
    ticketUrl: "https://thehookmpls.com",
    imageUrl: "/images/concert-rock.jpg",
    description:
      "Minneapolis psych-rock band Night Moves brings their dreamy, Fleetwood Mac-influenced sound to the Hook.",
    popularity: 35,
    isLocalArtist: true,
  },
  {
    id: "14",
    artist: "Caroline Smith",
    venue: venues.find((v) => v.id === "icehouse")!,
    date: getDate(11),
    time: "8:00 PM",
    doors: "7:00 PM",
    price: { min: 20, max: 25 },
    ageRestriction: "21+",
    genres: ["soul", "r&b"],
    mood: "chill",
    ticketUrl: "https://icehousempls.com",
    imageUrl: "/images/concert-jazz.jpg",
    description:
      "Minneapolis soul singer Caroline Smith performs songs spanning her evolution from folk to R&B. Powerful vocals in Icehouse's intimate room.",
    popularity: 45,
    isLocalArtist: true,
  },
  {
    id: "15",
    artist: "Communist Daughter",
    venue: venues.find((v) => v.id === "turf-club")!,
    date: getDate(12),
    time: "8:00 PM",
    doors: "7:00 PM",
    price: { min: 15, max: 20 },
    ageRestriction: "21+",
    genres: ["folk", "indie"],
    mood: "chill",
    ticketUrl: "https://turfclub.net",
    imageUrl: "/images/concert-folk.jpg",
    description:
      "Minneapolis folk-rock band Communist Daughter brings their haunting harmonies and cinematic arrangements to the Turf Club stage.",
    popularity: 30,
    isLocalArtist: true,
  },
  // Experimental / Weird
  {
    id: "16",
    artist: "Gaelynn Lea",
    venue: venues.find((v) => v.id === "cedar")!,
    date: getDate(15),
    time: "7:30 PM",
    doors: "6:30 PM",
    price: { min: 20, max: 28 },
    ageRestriction: "all-ages",
    genres: ["folk", "experimental"],
    mood: "experimental",
    ticketUrl: "https://thecedar.org",
    imageUrl: "/images/concert-folk.jpg",
    description:
      "NPR Tiny Desk contest winner Gaelynn Lea loops violin and voice into mesmerizing soundscapes. Hauntingly beautiful and utterly unique.",
    popularity: 40,
    isLocalArtist: true,
  },
  {
    id: "17",
    artist: "Marijuana Deathsquads",
    venue: venues.find((v) => v.id === "palmers")!,
    date: getDate(13),
    time: "10:00 PM",
    doors: "9:00 PM",
    price: { min: 10, max: 15 },
    ageRestriction: "21+",
    genres: ["experimental", "electronic"],
    mood: "experimental",
    ticketUrl: "https://palmersbar.net",
    imageUrl: "/images/concert-electronic.jpg",
    description:
      "Chaotic noise collective Marijuana Deathsquads (featuring members of Polica and Bon Iver) creates their signature controlled chaos at Palmer's.",
    popularity: 20,
    isLocalArtist: true,
  },
  // Big Shows
  {
    id: "18",
    artist: "Jason Isbell & The 400 Unit",
    venue: venues.find((v) => v.id === "armory")!,
    date: getDate(20),
    time: "8:00 PM",
    doors: "6:30 PM",
    price: { min: 55, max: 95 },
    ageRestriction: "all-ages",
    genres: ["country", "rock"],
    mood: "chill",
    ticketUrl: "https://armorymnpls.com",
    imageUrl: "/images/concert-folk.jpg",
    description:
      "Grammy-winning songwriter Jason Isbell brings his band The 400 Unit for a night of literate, emotionally devastating Americana.",
    popularity: 90,
    isLocalArtist: false,
  },
  {
    id: "19",
    artist: "Phoebe Bridgers",
    venue: venues.find((v) => v.id === "xcel")!,
    date: getDate(25),
    time: "8:00 PM",
    doors: "6:30 PM",
    price: { min: 45, max: 125 },
    ageRestriction: "all-ages",
    genres: ["indie", "folk"],
    mood: "chill",
    ticketUrl: "https://xcelenergycenter.com",
    imageUrl: "/images/concert-folk.jpg",
    description:
      "Indie-folk sensation Phoebe Bridgers brings her skeleton suits and sad songs to the Xcel. Tissues recommended.",
    popularity: 95,
    isLocalArtist: false,
  },
  // More Local / Obscure
  {
    id: "20",
    artist: "Alpha Consumer",
    venue: venues.find((v) => v.id === "clown-lounge")!,
    date: getDate(4),
    time: "10:00 PM",
    doors: "9:00 PM",
    price: { min: 8, max: 10 },
    ageRestriction: "21+",
    genres: ["punk", "experimental"],
    mood: "heavy",
    ticketUrl: "https://turfclub.net",
    imageUrl: "/images/concert-rock.jpg",
    description:
      "Ferocious Minneapolis hardcore in the Clown Lounge basement. Alpha Consumer delivers unrelenting noise punk fury.",
    popularity: 15,
    isLocalArtist: true,
  },
  {
    id: "21",
    artist: "Dreamland Faces",
    venue: venues.find((v) => v.id === "white-squirrel")!,
    date: getDate(6),
    time: "9:00 PM",
    doors: "8:00 PM",
    price: "free",
    ageRestriction: "21+",
    genres: ["electronic", "pop"],
    mood: "dancey",
    ticketUrl: "https://whitesquirrelbar.com",
    imageUrl: "/images/concert-electronic.jpg",
    description:
      "St Paul synth-pop act Dreamland Faces brings shimmering keyboards and catchy hooks to the White Squirrel's cozy stage.",
    popularity: 15,
    isLocalArtist: true,
  },
  {
    id: "22",
    artist: "Lazerbeak",
    venue: venues.find((v) => v.id === "can-can")!,
    date: getDate(7),
    time: "8:00 PM",
    doors: "7:00 PM",
    price: { min: 15, max: 20 },
    ageRestriction: "all-ages",
    genres: ["electronic", "hip-hop"],
    mood: "dancey",
    ticketUrl: "https://cancanwonderland.com",
    imageUrl: "/images/concert-electronic.jpg",
    description:
      "Doomtree producer Lazerbeak performs his solo instrumental work at Can Can Wonderland. Family-friendly beats among the mini golf and pinball.",
    popularity: 35,
    isLocalArtist: true,
  },
  // Suburbs
  {
    id: "23",
    artist: "Nelly",
    venue: venues.find((v) => v.id === "mystic-lake")!,
    date: getDate(30),
    time: "8:00 PM",
    doors: "7:00 PM",
    price: { min: 45, max: 85 },
    ageRestriction: "21+",
    genres: ["hip-hop", "r&b"],
    mood: "dancey",
    ticketUrl: "https://mysticlake.com",
    imageUrl: "/images/concert-hiphop.jpg",
    description:
      "2000s hip-hop hitmaker Nelly brings all the classics to Mystic Lake. It's getting hot in here.",
    popularity: 70,
    isLocalArtist: false,
  },
  {
    id: "24",
    artist: "Wilco",
    venue: venues.find((v) => v.id === "treasure-island")!,
    date: getDate(45),
    time: "7:00 PM",
    doors: "5:30 PM",
    price: { min: 55, max: 75 },
    ageRestriction: "all-ages",
    genres: ["rock", "indie", "country"],
    mood: "chill",
    ticketUrl: "https://treasureislandcasino.com",
    imageUrl: "/images/concert-rock.jpg",
    description:
      "Jeff Tweedy and Wilco perform under the stars at the Treasure Island Amphitheater. Bring a blanket and prepare for transcendence.",
    popularity: 75,
    isLocalArtist: false,
  },
  // More varied shows
  {
    id: "25",
    artist: "Low",
    venue: venues.find((v) => v.id === "cedar")!,
    date: getDate(18),
    time: "8:00 PM",
    doors: "7:00 PM",
    price: { min: 30, max: 40 },
    ageRestriction: "all-ages",
    genres: ["rock", "experimental"],
    mood: "experimental",
    ticketUrl: "https://thecedar.org",
    imageUrl: "/images/concert-rock.jpg",
    description:
      "Duluth slowcore pioneers Low continue to push boundaries. Their recent work is some of the most experimental and beautiful of their career.",
    popularity: 60,
    isLocalArtist: true,
  },
  {
    id: "26",
    artist: "Nur-D",
    venue: venues.find((v) => v.id === "varsity")!,
    date: getDate(16),
    time: "8:00 PM",
    doors: "7:00 PM",
    price: { min: 25, max: 35 },
    ageRestriction: "all-ages",
    genres: ["hip-hop", "pop"],
    mood: "dancey",
    ticketUrl: "https://varsitytheater.com",
    imageUrl: "/images/concert-hiphop.jpg",
    description:
      "Minneapolis rapper and 'nerd-hop' pioneer Nur-D brings his high-energy, positive vibes to the Varsity. Video game references and crowd participation guaranteed.",
    popularity: 50,
    isLocalArtist: true,
  },
  {
    id: "27",
    artist: "The Cactus Blossoms",
    venue: venues.find((v) => v.id === "turf-club")!,
    date: getDate(21),
    time: "8:00 PM",
    doors: "7:00 PM",
    price: { min: 25, max: 30 },
    ageRestriction: "21+",
    genres: ["country", "folk"],
    mood: "chill",
    ticketUrl: "https://turfclub.net",
    imageUrl: "/images/concert-folk.jpg",
    description:
      "Minneapolis brother duo The Cactus Blossoms bring their Everly Brothers-inspired harmonies home. Vintage country-pop perfection.",
    popularity: 45,
    isLocalArtist: true,
  },
  {
    id: "28",
    artist: "Heiruspecs",
    venue: venues.find((v) => v.id === "amsterdam")!,
    date: getDate(19),
    time: "9:00 PM",
    doors: "8:00 PM",
    price: { min: 20, max: 25 },
    ageRestriction: "21+",
    genres: ["hip-hop"],
    mood: "dancey",
    ticketUrl: "https://amsterdambarandhall.com",
    imageUrl: "/images/concert-hiphop.jpg",
    description:
      "Minneapolis hip-hop veterans Heiruspecs bring their live-band rap sound to Amsterdam. One of the Twin Cities' longest-running crews.",
    popularity: 35,
    isLocalArtist: true,
  },
  {
    id: "29",
    artist: "Haley",
    venue: venues.find((v) => v.id === "mortimers")!,
    date: getDate(5),
    time: "9:00 PM",
    doors: "8:00 PM",
    price: { min: 12, max: 15 },
    ageRestriction: "21+",
    genres: ["indie", "rock"],
    mood: "chill",
    ticketUrl: "https://mortimers.com",
    imageUrl: "/images/concert-folk.jpg",
    description:
      "Minneapolis songwriter Haley brings her powerful voice and confessional lyrics to Mortimer's intimate stage.",
    popularity: 20,
    isLocalArtist: true,
  },
  {
    id: "30",
    artist: "Birthday Suits",
    venue: venues.find((v) => v.id === "331-club")!,
    date: getDate(8),
    time: "10:00 PM",
    doors: "9:00 PM",
    price: "free",
    ageRestriction: "21+",
    genres: ["rock", "punk"],
    mood: "heavy",
    ticketUrl: "https://331club.com",
    imageUrl: "/images/concert-rock.jpg",
    description:
      "Minneapolis garage-punk duo Birthday Suits tear through their high-energy set. Just drums, guitar, and raw power.",
    popularity: 20,
    isLocalArtist: true,
  },
  // More shows for variety
  {
    id: "31",
    artist: "Polica",
    venue: venues.find((v) => v.id === "first-ave")!,
    date: getDate(28),
    time: "9:00 PM",
    doors: "8:00 PM",
    price: { min: 30, max: 40 },
    ageRestriction: "18+",
    genres: ["electronic", "pop"],
    mood: "dancey",
    ticketUrl: "https://first-avenue.com",
    imageUrl: "/images/concert-electronic.jpg",
    description:
      "Minneapolis electronic pop band Polica returns home. Channy Leaneagh's processed vocals over crushing beats.",
    popularity: 65,
    isLocalArtist: true,
  },
  {
    id: "32",
    artist: "Atmosphere",
    venue: venues.find((v) => v.id === "surly")!,
    date: getDate(35),
    time: "6:00 PM",
    doors: "4:00 PM",
    price: { min: 45, max: 55 },
    ageRestriction: "21+",
    genres: ["hip-hop"],
    mood: "chill",
    ticketUrl: "https://surlybrewing.com",
    imageUrl: "/images/concert-hiphop.jpg",
    description:
      "Minneapolis hip-hop legends Atmosphere play an outdoor summer show at Surly. Slug and Ant, together forever.",
    popularity: 80,
    isLocalArtist: true,
  },
  {
    id: "33",
    artist: "Dessa",
    venue: venues.find((v) => v.id === "dakota")!,
    date: getDate(22),
    time: "7:30 PM",
    doors: "6:30 PM",
    price: { min: 35, max: 50 },
    ageRestriction: "all-ages",
    genres: ["hip-hop", "pop", "classical"],
  mood: "chill",
  ticketUrl: "https://dakotacooks.com",
  imageUrl: "/images/concert-jazz.jpg",
    description:
      "Doomtree's Dessa performs with a string quartet. Her literate hip-hop and soaring vocals reimagined with classical arrangements.",
    popularity: 55,
    isLocalArtist: true,
  },
  {
    id: "34",
    artist: "Har Mar Superstar",
    venue: venues.find((v) => v.id === "7th-st-entry")!,
    date: getDate(17),
    time: "10:00 PM",
    doors: "9:00 PM",
    price: { min: 20, max: 25 },
    ageRestriction: "18+",
    genres: ["soul", "r&b", "pop"],
  mood: "dancey",
  ticketUrl: "https://first-avenue.com",
  imageUrl: "/images/concert-electronic.jpg",
    description:
      "Minneapolis soul man Har Mar Superstar brings his sweaty, sincere R&B to the Entry. A local legend.",
    popularity: 40,
    isLocalArtist: true,
  },
  {
    id: "35",
    artist: "Soul Asylum",
    venue: venues.find((v) => v.id === "fine-line")!,
    date: getDate(40),
    time: "8:00 PM",
    doors: "7:00 PM",
    price: { min: 35, max: 50 },
    ageRestriction: "21+",
    genres: ["rock"],
  mood: "heavy",
  ticketUrl: "https://fineline.com",
  imageUrl: "/images/concert-rock.jpg",
    description:
      "Minneapolis rock veterans Soul Asylum still bring the noise. Dave Pirner and crew play the hits and deep cuts.",
    popularity: 55,
    isLocalArtist: true,
  },
  {
    id: "36",
    artist: "The Suburbs",
    venue: venues.find((v) => v.id === "turf-club")!,
    date: getDate(32),
    time: "8:00 PM",
    doors: "7:00 PM",
    price: { min: 25, max: 35 },
    ageRestriction: "21+",
    genres: ["rock", "punk"],
  mood: "heavy",
  ticketUrl: "https://turfclub.net",
  imageUrl: "/images/concert-rock.jpg",
    description:
      "Minneapolis new wave pioneers The Suburbs reunite for a rare show. 'Love Is The Law' and more from the early 80s scene.",
    popularity: 40,
    isLocalArtist: true,
  },
  {
    id: "37",
    artist: "Information Society",
    venue: venues.find((v) => v.id === "cabooze")!,
    date: getDate(38),
    time: "8:00 PM",
    doors: "7:00 PM",
    price: { min: 30, max: 40 },
    ageRestriction: "21+",
    genres: ["electronic", "pop"],
  mood: "dancey",
  ticketUrl: "https://cabooze.com",
  imageUrl: "/images/concert-electronic.jpg",
    description:
      "Minneapolis synth-pop legends Information Society perform 'What's On Your Mind' and more 80s hits.",
    popularity: 45,
    isLocalArtist: true,
  },
  {
    id: "38",
    artist: "Mayda",
    venue: venues.find((v) => v.id === "icehouse")!,
    date: getDate(23),
    time: "9:00 PM",
    doors: "8:00 PM",
    price: { min: 15, max: 20 },
    ageRestriction: "21+",
    genres: ["folk", "pop"],
  mood: "chill",
  ticketUrl: "https://icehousempls.com",
  imageUrl: "/images/concert-jazz.jpg",
    description:
      "Minneapolis singer-songwriter Mayda brings her genre-blending sound—part folk, part pop, all heart.",
    popularity: 25,
    isLocalArtist: true,
  },
  {
    id: "39",
    artist: "Aby Wolf",
    venue: venues.find((v) => v.id === "hook-ladder")!,
    date: getDate(26),
    time: "8:00 PM",
    doors: "7:00 PM",
    price: { min: 18, max: 22 },
    ageRestriction: "21+",
    genres: ["soul", "jazz", "experimental"],
  mood: "experimental",
  ticketUrl: "https://thehookmpls.com",
  imageUrl: "/images/concert-electronic.jpg",
    description:
      "Minneapolis vocalist Aby Wolf performs her avant-soul experiments. Collaborator with everyone from Bon Iver to Doomtree.",
    popularity: 30,
    isLocalArtist: true,
  },
  {
    id: "40",
    artist: "Brother Ali",
    venue: venues.find((v) => v.id === "first-ave")!,
    date: getDate(42),
    time: "8:00 PM",
    doors: "7:00 PM",
    price: { min: 30, max: 40 },
    ageRestriction: "18+",
    genres: ["hip-hop"],
  mood: "heavy",
  ticketUrl: "https://first-avenue.com",
  imageUrl: "/images/concert-rock.jpg",
    description:
      "Rhymesayers rapper Brother Ali brings his powerful, politically-charged hip-hop home. One of the cities' most respected MCs.",
    popularity: 65,
    isLocalArtist: true,
  },
  // Even more variety
  {
    id: "41",
    artist: "Frogleg",
    venue: venues.find((v) => v.id === "331-club")!,
    date: getDate(11),
    time: "10:00 PM",
    doors: "9:00 PM",
    price: "free",
    ageRestriction: "21+",
    genres: ["jazz", "funk"],
  mood: "dancey",
  ticketUrl: "https://331club.com",
  imageUrl: "/images/concert-electronic.jpg",
    description:
      "Minneapolis jazz-funk collective Frogleg brings their improvisational grooves to the 331. Get weird, get dancey.",
    popularity: 20,
    isLocalArtist: true,
  },
  {
    id: "42",
    artist: "Black Diet",
    venue: venues.find((v) => v.id === "palmers")!,
    date: getDate(10),
    time: "10:00 PM",
    doors: "9:00 PM",
    price: { min: 10, max: 12 },
    ageRestriction: "21+",
    genres: ["rock", "blues"],
  mood: "heavy",
  ticketUrl: "https://palmersbar.net",
  imageUrl: "/images/concert-rock.jpg",
    description:
      "Minneapolis rock band Black Diet brings their raw, blues-influenced rock to Palmer's. Loud, sweaty, real.",
    popularity: 25,
    isLocalArtist: true,
  },
  {
    id: "43",
    artist: "Kiss The Tiger",
    venue: venues.find((v) => v.id === "turf-club")!,
    date: getDate(24),
    time: "9:00 PM",
    doors: "8:00 PM",
    price: { min: 15, max: 20 },
    ageRestriction: "21+",
    genres: ["rock", "punk"],
  mood: "heavy",
  ticketUrl: "https://turfclub.net",
  imageUrl: "/images/concert-rock.jpg",
    description:
      "Minneapolis rock band Kiss The Tiger brings fierce energy and anthemic songs. Front woman Meghan Kreidler commands the stage.",
    popularity: 30,
    isLocalArtist: true,
  },
  {
    id: "44",
    artist: "Yam Haus",
    venue: venues.find((v) => v.id === "fine-line")!,
    date: getDate(27),
    time: "8:00 PM",
    doors: "7:00 PM",
    price: { min: 20, max: 28 },
    ageRestriction: "18+",
    genres: ["pop", "rock"],
  mood: "dancey",
  ticketUrl: "https://fineline.com",
  imageUrl: "/images/concert-electronic.jpg",
    description:
      "Minneapolis pop-rock band Yam Haus brings their catchy hooks and high energy home. Ready for the big time.",
    popularity: 45,
    isLocalArtist: true,
  },
  {
    id: "45",
    artist: "Gully Boys",
    venue: venues.find((v) => v.id === "7th-st-entry")!,
    date: getDate(29),
    time: "9:00 PM",
    doors: "8:00 PM",
    price: { min: 15, max: 18 },
    ageRestriction: "18+",
    genres: ["punk", "indie"],
  mood: "heavy",
  ticketUrl: "https://first-avenue.com",
  imageUrl: "/images/concert-rock.jpg",
    description:
      "Minneapolis queer punk trio Gully Boys bring their anthems of resilience and rage to the Entry.",
    popularity: 40,
    isLocalArtist: true,
  },
  {
    id: "46",
    artist: "Eleganza",
    venue: venues.find((v) => v.id === "can-can")!,
    date: getDate(31),
    time: "9:00 PM",
    doors: "8:00 PM",
    price: { min: 15, max: 20 },
    ageRestriction: "all-ages",
    genres: ["pop", "electronic"],
  mood: "dancey",
  ticketUrl: "https://cancanwonderland.com",
  imageUrl: "/images/concert-electronic.jpg",
    description:
      "Twin Cities drag and dance party Eleganza takes over Can Can Wonderland. Performances, DJs, and pure joy.",
    popularity: 35,
    isLocalArtist: true,
  },
  {
    id: "47",
    artist: "Erik Koskinen",
    venue: venues.find((v) => v.id === "hook-ladder")!,
    date: getDate(33),
    time: "8:00 PM",
    doors: "7:00 PM",
    price: { min: 18, max: 22 },
    ageRestriction: "21+",
    genres: ["country", "folk"],
  mood: "chill",
  ticketUrl: "https://thehookmpls.com",
  imageUrl: "/images/concert-folk.jpg",
    description:
      "Minneapolis country songwriter Erik Koskinen brings his literate, working-class songs to the Hook. Real country for real people.",
    popularity: 30,
    isLocalArtist: true,
  },
  {
    id: "48",
    artist: "The Jayhawks",
    venue: venues.find((v) => v.id === "palace")!,
    date: getDate(50),
    time: "8:00 PM",
    doors: "7:00 PM",
    price: { min: 45, max: 65 },
    ageRestriction: "all-ages",
    genres: ["rock", "country", "folk"],
  mood: "chill",
  ticketUrl: "https://palacetheatre.us",
  imageUrl: "/images/concert-folk.jpg",
    description:
      "Minneapolis alt-country legends The Jayhawks return home. Gary Louris and crew play songs spanning four decades.",
    popularity: 70,
    isLocalArtist: true,
  },
  {
    id: "49",
    artist: "ZULUZULUU",
    venue: venues.find((v) => v.id === "icehouse")!,
    date: getDate(34),
    time: "10:00 PM",
    doors: "9:00 PM",
    price: { min: 15, max: 20 },
    ageRestriction: "21+",
    genres: ["hip-hop", "soul", "r&b"],
  mood: "dancey",
  ticketUrl: "https://icehousempls.com",
  imageUrl: "/images/concert-electronic.jpg",
    description:
      "Minneapolis Afrofuturist collective ZULUZULUU brings their genre-blending sound. Hip-hop, soul, funk, and more.",
    popularity: 35,
    isLocalArtist: true,
  },
  {
    id: "50",
    artist: "Astralblak",
    venue: venues.find((v) => v.id === "amsterdam")!,
    date: getDate(36),
    time: "9:00 PM",
    doors: "8:00 PM",
    price: { min: 18, max: 22 },
    ageRestriction: "21+",
    genres: ["hip-hop", "electronic"],
  mood: "dancey",
  ticketUrl: "https://amsterdambarandhall.com",
  imageUrl: "/images/concert-hiphop.jpg",
    description:
      "Minneapolis producer and rapper Astralblak brings cosmic hip-hop vibes. Founder of the Astral Records collective.",
    popularity: 25,
    isLocalArtist: true,
  },
  
  // Comedy Events
  {
    id: "52",
    artist: "Maria Bamford",
    venue: venues.find((v) => v.id === "acme-comedy")!,
    date: getDate(1),
    time: "8:00 PM",
    doors: "7:00 PM",
    price: { min: 35, max: 45 },
    ageRestriction: "21+",
    genres: ["comedy"],
    mood: "chill",
    ticketUrl: "https://acmecomedycompany.com",
    imageUrl: "/images/concert-comedy.jpg",
    description:
      "Minneapolis native Maria Bamford returns home with her uniquely absurdist stand-up. Known for Lady Dynamite and her pioneering work in mental health comedy.",
    popularity: 75,
    isLocalArtist: true,
  },
  {
    id: "53",
    artist: "Open Mic Comedy Night",
    venue: venues.find((v) => v.id === "sisyphus")!,
    date: getDate(2),
    time: "8:00 PM",
    doors: "7:30 PM",
    price: "free",
    ageRestriction: "21+",
    genres: ["comedy"],
    mood: "chill",
    ticketUrl: "https://sisyphusbrewing.com",
    imageUrl: "/images/concert-comedy.jpg",
    description:
      "Weekly open mic showcasing emerging Twin Cities comedians. Great beer, great laughs, no cover.",
    popularity: 15,
    isLocalArtist: true,
  },
  {
    id: "54",
    artist: "Nate Bargatze",
    venue: venues.find((v) => v.id === "mystic-lake")!,
    date: getDate(7),
    time: "7:30 PM",
    doors: "6:30 PM",
    price: { min: 55, max: 85 },
    ageRestriction: "21+",
    genres: ["comedy"],
    mood: "chill",
    ticketUrl: "https://mysticlake.com",
    imageUrl: "/images/concert-comedy.jpg",
    description:
      "The Raincheck Tour. Nate Bargatze brings his wholesome, deadpan humor on his latest national tour.",
    popularity: 90,
    isLocalArtist: false,
  },
  {
    id: "55",
    artist: "HUGE Improv: The Main Event",
    venue: venues.find((v) => v.id === "huge-theater")!,
    date: getDate(3),
    time: "9:00 PM",
    doors: "8:30 PM",
    price: { min: 10, max: 15 },
    ageRestriction: "18+",
    genres: ["comedy"],
    mood: "chill",
    ticketUrl: "https://hugetheater.com",
    imageUrl: "/images/concert-comedy.jpg",
    description:
      "HUGE Theater's flagship improv show featuring their top house teams. Unscripted comedy at its finest.",
    popularity: 40,
    isLocalArtist: true,
  },
  {
    id: "56",
    artist: "Pete Lee",
    venue: venues.find((v) => v.id === "house-of-comedy")!,
    date: getDate(5),
    time: "8:00 PM",
    doors: "7:00 PM",
    price: { min: 25, max: 35 },
    ageRestriction: "21+",
    genres: ["comedy"],
    mood: "chill",
    ticketUrl: "https://houseofcomedy.net",
    imageUrl: "/images/concert-comedy.jpg",
    description:
      "Minnesota-born comedian Pete Lee, winner of Last Comic Standing, returns to his home state. Late Night with Seth Meyers regular.",
    popularity: 60,
    isLocalArtist: true,
  },
  {
    id: "57",
    artist: "Comedy Corner Showcase",
    venue: venues.find((v) => v.id === "comedy-corner")!,
    date: getDate(4),
    time: "8:30 PM",
    doors: "8:00 PM",
    price: { min: 12, max: 15 },
    ageRestriction: "21+",
    genres: ["comedy"],
    mood: "chill",
    ticketUrl: "https://comedycornerunderground.com",
    imageUrl: "/images/concert-comedy.jpg",
    description:
      "Underground comedy showcase featuring rising Twin Cities comedians. Intimate basement venue with a raw, DIY vibe.",
    popularity: 20,
    isLocalArtist: true,
  },
  {
    id: "58",
    artist: "Hari Kondabolu",
    venue: venues.find((v) => v.id === "cedar")!,
    date: getDate(12),
    time: "7:30 PM",
    doors: "7:00 PM",
    price: { min: 28, max: 35 },
    ageRestriction: "all-ages",
    genres: ["comedy"],
    mood: "chill",
    ticketUrl: "https://thecedar.org",
    imageUrl: "/images/concert-comedy.jpg",
    description:
      "Politically-charged stand-up from Hari Kondabolu. Known for The Problem with Apu documentary and sharp social commentary.",
    popularity: 55,
    isLocalArtist: false,
  },
  {
    id: "59",
    artist: "Acme All-Stars",
    venue: venues.find((v) => v.id === "acme-comedy")!,
    date: getDate(6),
    time: "10:30 PM",
    doors: "10:00 PM",
    price: { min: 15, max: 20 },
    ageRestriction: "21+",
    genres: ["comedy"],
    mood: "chill",
    ticketUrl: "https://acmecomedycompany.com",
    imageUrl: "/images/concert-comedy.jpg",
    description:
      "Late night showcase featuring Acme's best local comedians. A rotating lineup of Twin Cities comedy favorites.",
    popularity: 35,
    isLocalArtist: true,
  },
]

// Helper functions
export function getEventById(id: string): Event | undefined {
  return events.find((e) => e.id === id)
}

export function getVenueById(id: string): Venue | undefined {
  return venues.find((v) => v.id === id)
}

export function getEventsByVenue(venueId: string): Event[] {
  return events.filter((e) => e.venue.id === venueId)
}

export function getEventsByNeighborhood(neighborhood: Neighborhood): Event[] {
  return events.filter((e) => e.venue.neighborhood === neighborhood)
}

export function getTonightEvents(): Event[] {
  const today = new Date().toISOString().split("T")[0]
  return events.filter((e) => e.date === today)
}

export function getWeekendEvents(): Event[] {
  const today = new Date()
  const dayOfWeek = today.getDay()

  // Calculate days until Friday (5) and Sunday (0 next week)
  const daysUntilFriday = dayOfWeek <= 5 ? 5 - dayOfWeek : 5 + (7 - dayOfWeek)
  const daysUntilSunday = daysUntilFriday + 2

  const friday = new Date(today)
  friday.setDate(today.getDate() + daysUntilFriday)

  const sunday = new Date(today)
  sunday.setDate(today.getDate() + daysUntilSunday)

  const fridayStr = friday.toISOString().split("T")[0]
  const sundayStr = sunday.toISOString().split("T")[0]

  return events.filter((e) => e.date >= fridayStr && e.date <= sundayStr)
}

export function getUpcomingEvents(limit?: number): Event[] {
  const today = new Date().toISOString().split("T")[0]
  const upcoming = events
    .filter((e) => e.date >= today)
    .sort((a, b) => a.date.localeCompare(b.date))

  return limit ? upcoming.slice(0, limit) : upcoming
}
